### PR TITLE
Fix on Cljs 1.10.238

### LINKED ISSUE #6: MapEntry broken on ClojureScript 1.10.238
In new ClojureScript, `key` and `val` functions only work on proper `MapEntry` objects, but `linked` creates `vector` for map-entries:

https://github.com/frankiesardo/linked/blob/master/src/linked/map.cljc#L259

https://clojurescript.org/news/2018-03-26-release#_map_entries

This breaks e.g. `(key (first (linked/map ...)))`.

### PR DESCRIPTION
**Pull request by Deraen**
Fixes #6

### CODE REVIEW

**Comment by frankiesardo** [comment]
Thank you 🎩

**Comment by Deraen** [comment]
@frankiesardo I'd recommend rewriting circle.yml to use Circle v2, like this:

```yml
version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/clojure:boot-2.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "boot.properties" }}-{{ checksum "build.boot" }}
            - v1-
      - run: boot test
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: v1-{{ checksum "boot.properties" }}-{{ checksum "build.boot" }}
```

Not sure what to do with `deployment` part. Maybe second job using same Boot image and running `boot deploy`. And then adding `workflow` to run `deploy` job if branch is master etc: https://circleci.com/docs/2.0/deployment-integrations/

**Comment by Deraen** [comment]
But as a quick fix, you could update the download here https://github.com/frankiesardo/linked/blob/master/circle.yml#L6

to download https://github.com/boot-clj/boot-bin/releases/download/2.7.2/boot.sh

**Comment by frankiesardo** [comment]
Thanks but I think in the next future I'd like to move the project to deps.edn

**Pull request merged**
