### PR TITLE
Use CircleCI v2

### PR DESCRIPTION
**Pull request by Deraen**
This should take care of fixing CI: https://circleci.com/gh/metosin/linked/3

I don't know about the deploy step but I think runs the same command as before so hopefully that works also. The deploy is ran as separate job after test job.

Github is showing test failure for master branch in my fork, as it was trying to run deploy.

### CODE REVIEW

**Comment by Deraen** [comment]
Deploy seems to be stuck asking password for dotfiles git repository, hmm. Looks like it is using https git instead of ssh, how should the authentication work?

**Comment by frankiesardo** [comment]
Hi @Deraen thanks for looking into this. This is one if the things I set up a while back and worked fine until it didn't because of a combination of boot and circleci. Will see if I can fix it myself moving back to Leiningen. I know this is blocking some work on your side and I'm sorry for that, but I guess you can deploy a snapshot of metosin/linked yourself until this is fixed am I right? Best. F.

**Comment by Deraen** [comment]
Ah, I just looked into this as Tommi mentioned CircleCI problems.

Looks like the deploy problem is caused by `git clone $DOTFILES ~/dotfiles`, not Boot. Not sure what causes this difference with CircleCI v1 and v2. Anyway, I think you'll want to disable the used token from bitbucket because **this build log contains the token**: https://circleci.com/gh/frankiesardo/linked/69

Anyway, for leiningen and tools-deps, check these docker containers you can use: https://hub.docker.com/r/circleci/clojure/tags/
Docs also have lots of examples https://circleci.com/docs/2.0/language-clojure/
And hopefully new circleci config will be easy to convert to Lein or tools-deps.

**Comment by ikitommi** [comment]
Off to countryside, I did a fork under ikitommi to get the alpha depending on this out. There was actually a code bug, that appeares only after porting to Leingen. Worked ok with boot.

https://github.com/ikitommi/linked/commit/a0daf02b9289ed86f1826bdc27f61583bfcc95ad

thanks for working on this. We'll update to latest official when out.

**Pull request merged**
